"""updated monthly expense

Revision ID: 7996f3fcd6c5
Revises: 52e94b42d9f0
Create Date: 2025-12-10 11:14:54.355122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7996f3fcd6c5'
down_revision = '52e94b42d9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income')
    with op.batch_alter_table('monthly_expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income', sa.Numeric(precision=12, scale=2), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_expense', schema=None) as batch_op:
        batch_op.drop_column('income')

    op.create_table('income',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('income_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('income_pkey'))
    )
    # ### end Alembic commands ###
